language: ruby
rvm:
  - 2.4.3

before_script: bundle exec jekyll build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: travis_retry bundle exec htmlproofer --check-html --internal_domains "/www.ournetworks.ca/,/ournetworks.ca/" ./_site

deploy:
  provider: script
  script: bash scripts/deploy.sh $USER $PASSWORD
  on:
    branch: master

notifications:
  email:
    recipients:
      - orga@ournetworks.ca
    on_failure: always
