language: ruby
rvm:
  - 2.6.0

before_install:
  # Here, we decrypt a passwordless ssh key for acting as a user on the server named "travis"
  # See: https://docs.travis-ci.com/user/encrypting-files/#Automated-Encryption
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_a3d58fa41b45_key -iv $encrypted_a3d58fa41b45_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then chmod 400 scripts/id_rsa; fi
  # Bundler 2.0 support
  # See: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem update --system
  - gem install bundler
  # Install NVM with Dat via npm
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  - nvm install 10.16.0
  - npm i -g dat

before_script:
  # Build Jekyll site
  - bundle exec jekyll build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: DLsGHnFx8YUuVVsqv+7nWlHFlRVnufpO7ZBAAUQxY0DXKBwRuYpVZxaGrCjktSt8086QnrNhRIhyM3mSVA6X5I730GVKJn+oWfIHwezg30Gx4Et/boEbyEb8q8hRJmOr2E6bEWEwamG8mfx2qWW46/jv03IbHjKjRDfuP2VcHkv5fWgLtsN5uWk7EL4Fbn6ZXa0d036YWBS2iO5N/b96K7Fm1K8YwxdZ7O4h0eFNReKK/TqHRcQJnkyGzdQoWXA9kOVblC1VH6t64xtp/aTH33/vd37zVY7T0Q1yeghp6TKl1qvwJ9wtAk/lmK++TQVU6GrJVTtawaenJ8Hxnkjy0Y2AAIVeLrPNWuZ9w1bxUHd4duTbreSXQ26PurFCcC8WFgNU1BEr8xLnDzFhcVpg/rG5aBKh9QUKkJfw6pjlVidNma7aD/uZHdppMUgRJmmofbTp3iOlESEch4YAyvFaVlLiKPo/hxbQ4pDn6E5W+cHdPD7dDOExVeClP6UVjrVX1dHDLotLuJA3Cxj/pI5RMYPpiXHoyFnUTF4wbn1VRVCP7lZVLDe54mRz2Pp5ha7mpQXkBC9LV18YsBJ+LZv+36zhdxGeLlRPdzd8Ah672dvDhSQt4pswzn2LetJl/9mBHXvl+S9518e/us3JI2g6WrhCAEH2CsayOtUtDbTVCh0=

cache: bundler

script: travis_retry bundle exec htmlproofer --check-html --allow-hash-href --internal_domains "/www.ournetworks.ca/,/ournetworks.ca/" ./_site

deploy:
  # Cleanup removes keys and build artefacts.
  # See: https://docs.travis-ci.com/user/deployment/#Uploading-Files-and-skip_cleanup
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh travis scripts/id_rsa ournetworks.ca
  on:
    branch:
      - master

after_deploy:
  # Clone/Initialize Dat archive
  - dat clone $(head -n 1 .well-known/dat) ./_site --exit
  # Build Jekyll site
  - bundle exec jekyll build
  - cd _site
  - echo $DATKEY | dat keys import
  - travis_wait 1 dat sync &> /dev/null || travis_terminate 0

notifications:
  email:
    recipients:
      - orga@ournetworks.ca
    on_success: change
    on_failure: change
