language: ruby
rvm:
  - 2.4.3

before_install:
  - openssl aes-256-cbc -K $encrypted_a3d58fa41b45_key -iv $encrypted_a3d58fa41b45_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d

before_script: bundle exec jekyll build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: travis_retry bundle exec htmlproofer --check-html --internal_domains "/www.ournetworks.ca/,/ournetworks.ca/" ./_site

deploy:
  # Otherwise, travis assumes you want to clean up workspace after tests
  # With cleanup, we wouldn't have build artefact or SSH keys
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch:
      - master
      - travis-deploy

notifications:
  email:
    recipients:
      - orga@ournetworks.ca
    on_failure: always
