language: ruby
rvm:
  - 2.4.3

before_script: bundle exec jekyll build

script: travis_retry bundle exec htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false