language: ruby
rvm:
  - 2.6.0

before_install:
  # Here, we decrypt a passwordless ssh key for acting as a user on the server named "travis"
  # See: https://docs.travis-ci.com/user/encrypting-files/#Automated-Encryption
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_a3d58fa41b45_key -iv $encrypted_a3d58fa41b45_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then chmod 400 scripts/id_rsa; fi
  # Bundler 2.0 support
  # See: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem update --system
  - gem install bundler
  # Install NVM with Dat via npm
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  - nvm install 10.15.3
  - npm i -g dat

before_script:
  # Clone/Initialize Dat archive
  - travis_wait 1 dat clone $(head -n 1 .well-known/dat) ./_site --exit
  # Build Jekyll site
  - bundle exec jekyll build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: pJiHauzABSvNLS6Hss0mPsKWUuPdBRaPd8s7pXgsKtpM2s/DCiOQW0niyRMsh7GAOlD0CwgwllOgRE81B7WN/LX5i32yQ/6HIIjLTgS42Q51U5CGeWH57YaKSSk5cNgZABtrHYUy+WGFO3aWQQQ/7lxR1wWfFvKE5Zf302mTQ6X6bQ6hg813SEG3vpDkSY+Cl2TBo7MUq7k6vINdzmCkI08ytci7AAvn6DOQab1RaHd+cGuHNM+rhyHztPzWlM+fwgagO+8gShNxmA3702prQ5nSK04in5i/yb+o0Urs2WZXJcZq5dgCUeYG2VXND93nMRGTksbewyvCn2i9jur1Q4/2bUDQRg80s1vh/qn21UtKuRtO+EFRSEArev+gALr+aHd2tfQAf0UFV6DLTQHndGvNxW0FwMji9Iq+msIZSvwIXaH0AY6Hk/+AlDqxIACdMAC76UQH5RpLeQGCns3AAypDZUEGJLBcUISQq6vYu3LMcYciQUAIhpv0yP541WGd+mZVbDcspwwzCJvCQL0+pcGuQQSmriyetPlC33Iqj0cDpst5LfOmIwNgm3K/OuigXDJn6Q2Nc4+CL/NJLqf82CQFNSBSgy9OA46KPLxsOwcoAftbGcaE6nJWxwFbLu2m6GGGNBMquNgdVYhW6ODPdMluyRP1B0QuxRNl7Y5icZU=

cache: bundler

script: travis_retry bundle exec htmlproofer --check-html --allow-hash-href --internal_domains "/www.ournetworks.ca/,/ournetworks.ca/" ./_site

deploy:
  # Cleanup removes keys and build artefacts.
  # See: https://docs.travis-ci.com/user/deployment/#Uploading-Files-and-skip_cleanup
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh travis scripts/id_rsa ournetworks.ca
  on:
    branch:
      - master

after_deploy:
  - cd _site
  - echo $DATKEY | dat keys import
  - travis_wait 1 dat sync --no-watch || travis_terminate 0

notifications:
  email:
    recipients:
      - orga@ournetworks.ca
    on_success: change
    on_failure: change
