language: ruby
rvm:
  - 2.6.0

before_install:
  # Here, we decrypt a passwordless ssh key for acting as a user on the server named "travis"
  # See: https://docs.travis-ci.com/user/encrypting-files/#Automated-Encryption
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_a3d58fa41b45_key -iv $encrypted_a3d58fa41b45_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then chmod 400 scripts/id_rsa; fi
  # Bundler 2.0 support
  # See: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem update --system
  - gem install bundler
  # Install NVM with Dat via npm
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  - nvm install 10.16.0
  - npm i -g dat

before_script:
  # Build Jekyll site
  - bundle exec jekyll build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: OhpI3d+KIwUiKC7FR4JGoPbVXmtyzKi/DAAUvD+JW2fgyirP2h6VRGdmgO5VaeYdacD2BEnQeHjmyX3OBb7i3nsyAaMnnPhD4m0NqLvU1nVGjF9/SFxBz4g16S4eOE5ZjxxRf1aL27vSuTgnxkC1MYEPWoXWTfFjLa6EsABFh4UCIYK2ioVf28eJdmtzhIWJoqAZ76HO/yw/pPeAQZmboAaSZjOcWfiYg7phdnuIzwn1ovAf0S7B85ihI9YPzHDnK4pJOd/e/3P1nIzJljhgU1jZpHADzH58zonBHrlkX7F9jct4y19eVuma9V+D1CxWsJPYgpXvNN2uw+GtIXjmttSS1lpro39vO+Siz0FVLQlQu4Xvb8SWsOhXB+Vn+CknHQfsckbhHXykE80UYNN1AXJ8NDoMuZJnYMp3LF3uG7ELQ4rqNOSSkQsp6+zFEK0RcAYoK8uBmZHw+1n5lOjXwaSPki+ltTYYFMv3zclgMTiiTtq1DhOQMr6TWiVC32y1cfg6JATbPzD2XwLg5MuluXm6uL5HlN0AkOFpvu3FFmM1jzOpzcKLGokRQP7H/LpczLRMdRShGWNuipTI3vOLx33+BhEkuZTItczVPWhOG8tJnSfCl6+kyIIEsuHi+dzaTsPwoUYTYL25/HQRvnBbmw6xD6YTSazu85wn3/Gq8W8=

cache: bundler

script: travis_retry bundle exec htmlproofer --check-html --allow-hash-href --internal_domains "/www.ournetworks.ca/,/ournetworks.ca/" ./_site

deploy:
  # Cleanup removes keys and build artefacts.
  # See: https://docs.travis-ci.com/user/deployment/#Uploading-Files-and-skip_cleanup
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh travis scripts/id_rsa ournetworks.ca
  on:
    branch:
      - master

after_deploy:
  # Clone/Initialize Dat archive
  - dat $(head -n 1 .well-known/dat) ./_site --exit
  # Build Jekyll site
  - bundle exec jekyll build
  - cd _site
  - echo $DATKEY | dat keys import
  - travis_wait 1 dat sync &> /dev/null || travis_terminate 0

notifications:
  email:
    recipients:
      - orga@ournetworks.ca
    on_success: change
    on_failure: change
